export const projectCategories = [
  { id: "all", label: "全部精选", eyebrow: "SELECTED WORK" },
  { id: "agent", label: "智能体系统", eyebrow: "INTELLIGENT AGENTS" },
  { id: "infra", label: "AI 基础设施", eyebrow: "AI INFRASTRUCTURE" },
  { id: "lab", label: "研究与安全", eyebrow: "RESEARCH LABS" },
];

export const projectsData = [
  {
    id: "enterprise-agentic-rag",
    number: "01",
    name: "Enterprise Agentic RAG",
    categoryId: "agent",
    category: "企业级知识智能体",
    summary: "让企业知识问答从“像答案”，变成可以回到原文页码和证据的答案。",
    challenge: "知识散落在 PDF、DOCX、XLSX 与 Wiki 中，单纯向量检索难以同时保证召回、证据定位和访问控制。",
    solution: "设计 Root / Leaf 切块、Dense + BM25 混合检索、RRF 融合、CrossEncoder 重排与页级引用，并在查询前收窄 ACL。",
    outcome: "CPU 环境 240 条分层样本中，Fusion Top-10 文档召回率 97.92%，页命中率 95.00%，证据命中率 90.83%。",
    evidence: "240 条分层离线样本 · CPU 测试口径",
    tags: ["LangGraph", "Milvus", "BGE-M3", "RRF", "RBAC"],
    year: "2026",
    link: "https://github.com/hey-Chloe/enterprise-agentic-rag",
    linkLabel: "查看公开仓库",
  },
  {
    id: "reminder-cat",
    number: "02",
    name: "ReminderCat",
    categoryId: "agent",
    category: "企业微信提醒 Agent",
    summary: "在企业微信里说一句话，Agent 就能理解提醒、可靠调度，并在正确时间主动送达。",
    challenge: "自然语言时间表达模糊，企业微信回调只有 5 秒窗口，重复消息、投递失败和进程重启都可能破坏提醒。",
    solution: "用 LLM 生成结构化意图，通过 ToolRegistry 执行工具；加入 AES 回调验证、msgId 幂等、异步回执和可恢复调度。",
    outcome: "已完成企业微信移动端端到端验收，并以 Docker、Nginx 部署到阿里云 ECS；失败任务按 60 / 120 / 240 秒退避重试。",
    evidence: "真实企业微信端到端验收 · 已部署",
    tags: ["Java 21", "Spring Boot", "DeepSeek", "Tool Registry", "PostgreSQL"],
    year: "2026",
    link: "https://github.com/hey-Chloe/ReminderCat",
    linkLabel: "查看公开仓库",
  },
  {
    id: "mini-claude-code",
    number: "03",
    name: "MiniClaudeCode",
    categoryId: "agent",
    category: "Coding Agent Runtime",
    summary: "一个会规划、调用工具、控制副作用、恢复会话并验证修改结果的 Coding Agent Runtime。",
    challenge: "长任务中，Agent 容易反复读取、遗忘目标、越权执行，或者在第一次失败后丢失可恢复状态。",
    solution: "实现有界执行循环、JSON Schema 工具、ALLOW / ASK / DENY 策略、上下文压缩、检查点、追踪、MCP stdio 与评测。",
    outcome: "离线确定性夹具验证 26 / 26 通过，用来验证 Runtime 行为与恢复契约，不把它包装成模型能力成绩。",
    evidence: "26 / 26 离线 Runtime 夹具 · 非模型质量指标",
    tags: ["Python", "Tool Calling", "MCP", "Docker", "Policy Engine"],
    year: "2026",
    link: "https://github.com/hey-Chloe/MiniClaudeCode",
    linkLabel: "查看公开仓库",
  },
  {
    id: "kai-cloudpay",
    number: "04",
    name: "KAI CloudPay",
    categoryId: "infra",
    category: "AI 算力交易基础设施",
    summary: "把资源验证、双重审核、卡时购买、履约、售后与结算串成同一条可审计交易链。",
    challenge: "供应主体、算力资源、价格、订单、履约和账本跨越多个边界，状态漂移会直接放大交易与资金风险。",
    solution: "围绕交易主体、资源、Offer 双审、KAI 卡时订单、证据、幂等和复式账本建立单一领域规则来源。",
    outcome: "已实现移动端买家 / 供应商双视角、KAI 卡时算力订单与实物设备订单；这里展示实现范围，不宣称线上经营数据。",
    evidence: "私有项目 · 实现范围说明",
    tags: ["Expo 57", "Fastify", "PostgreSQL", "OIDC", "Double-entry Ledger"],
    year: "2026",
    link: null,
    linkLabel: "Private Case Study",
  },
  {
    id: "okr-agent-platform",
    number: "05",
    name: "OKR Agent Platform",
    categoryId: "agent",
    category: "企业级 Agent 平台",
    summary: "让自然语言查询经过组织权限、版本化工作流和可靠 Worker，而不是让模型直接访问企业数据。",
    challenge: "组织、部门和租户边界会随业务变化；异步执行还需要版本、重试、恢复和完整审计。",
    solution: "组合 RBAC + ABAC、不可变工作流版本、DAG、Worker Lease、重试 / DLQ、检查点和统一模型网关。",
    outcome: "把模型调用约束在可授权、可恢复、可追踪的平台边界内；暂不展示尚未进入公开仓库的本地性能数据。",
    evidence: "公开架构与实现 · 性能数据待发布后披露",
    tags: ["FastAPI", "PostgreSQL", "Redis", "RBAC / ABAC", "OpenTelemetry"],
    year: "2026",
    link: "https://github.com/hey-Chloe/okr-agent-platform",
    linkLabel: "查看公开仓库",
  },
  {
    id: "mini-runtime-agent",
    number: "L1",
    name: "mini Runtime Agent",
    categoryId: "lab",
    category: "轻量 Agent Runtime",
    summary: "不用 Agent 框架，从标准库开始理解有界循环、上下文、状态与追踪。",
    challenge: "框架封装让执行循环和失败语义变得难以观察，也不利于验证最小可用边界。",
    solution: "从 stdlib 构建有界循环、SQLite 状态、上下文预算与执行轨迹，保留每个关键决策。",
    outcome: "作为 Runtime 机制实验保留，重点是可解释的执行边界，不包装成独立商业产品。",
    evidence: "本地研究项目",
    tags: ["Python", "SQLite", "Bounded Loop", "Tracing"],
    year: "2026",
    link: null,
    linkLabel: "Research Note",
  },
  {
    id: "ctf-agent",
    number: "L2",
    name: "CTF Agent",
    categoryId: "lab",
    category: "授权安全执行实验",
    summary: "在明确授权和沙箱边界内，让 Agent 多步探索、调用工具并保留操作轨迹。",
    challenge: "安全任务需要多步探索，但不受控的命令执行和隐式状态会带来新的风险。",
    solution: "用工具白名单、容器边界、检查点和失败分类约束执行，让任务可以暂停、审查与继续。",
    outcome: "目前作为授权环境中的工程实验展示，只描述已实现能力，不宣称缺少评测支撑的成绩。",
    evidence: "仅限授权环境",
    tags: ["LangGraph", "Docker", "Checkpoint", "Security"],
    year: "2026",
    link: null,
    linkLabel: "Research Note",
  },
  {
    id: "quant-strategy-evolver",
    number: "L3",
    name: "Quant Strategy Evolver",
    categoryId: "lab",
    category: "研究型评测管线",
    summary: "让策略生成接受样本外验证和约束检查，主动暴露过拟合，而不是只展示漂亮收益曲线。",
    challenge: "生成式策略很容易在单一回测窗口中看起来有效，却无法通过样本外约束。",
    solution: "建立候选生成、回测、约束、样本外评估与结果归档流程，把失败也作为研究结果。",
    outcome: "默认合成样本的 OOS 结果未通过约束，项目价值在于识别过拟合，不以收益宣传。",
    evidence: "研究实验 · 非投资建议",
    tags: ["Python", "Backtesting", "Evaluation", "OOS"],
    year: "2026",
    link: null,
    linkLabel: "Research Note",
  },
];

export const BtnList = [
  { label: "首页", link: "/", icon: "home", newTab: false },
  { label: "关于小悦", link: "/about", icon: "about", newTab: false },
  { label: "项目", link: "/projects", icon: "projects", newTab: false },
  { label: "联系", link: "/contact", icon: "contact", newTab: false },
  { label: "GitHub", link: "https://github.com/hey-Chloe", icon: "github", newTab: true },
  { label: "邮箱", link: "mailto:xiaoyue0227@yeah.net", icon: "mail", newTab: true },
];
